# Generated by Django 2.2.16 on 2021-01-03 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parachutes', '0001_initial'),
        ('users', '0001_initial'),
        ('manifest', '0001_initial'),
        ('aircrafts', '0002_auto_20210103_1510'),
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='aircrafts',
            field=models.ManyToManyField(null=True, to='aircrafts.Aircraft'),
        ),
        migrations.AddField(
            model_name='tickets',
            name='bought_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.User'),
        ),
        migrations.AddField(
            model_name='tickets',
            name='flights',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='manifest.Flights'),
        ),
        migrations.AddField(
            model_name='tickets',
            name='luggage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='parachutes.Parachute'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='exit_height',
            field=models.CharField(choices=[('4000', 4000), ('2000', 2000), ('1000', 1000)], max_length=5),
        ),
    ]
