# Generated by Django 2.2.16 on 2021-01-03 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_auto_20210103_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='aircrafts',
            field=models.ManyToManyField(to='aircrafts.Aircraft'),
        ),
    ]
