# Generated by Django 2.2.16 on 2021-01-03 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210103_1510'),
        ('parachutes', '0001_initial'),
        ('manifest', '0002_auto_20210103_1510'),
        ('clubs', '0003_auto_20210103_1510'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tickets',
            new_name='Ticket',
        ),
    ]
