# Generated by Django 2.2.16 on 2021-01-01 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('permitted_starting_weight', models.DecimalField(decimal_places=0, max_digits=5)),
            ],
        ),
    ]
