# Generated by Django 2.2.16 on 2021-01-03 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aircrafts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeckArrangement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_pilot_seats', models.IntegerField(verbose_name='maximal number of pilots in arrangement')),
                ('max_passenger_seats', models.IntegerField(verbose_name='maximal number of passengers in arrangement')),
            ],
        ),
        migrations.AddField(
            model_name='aircraft',
            name='seats_configuration',
            field=models.ManyToManyField(to='aircrafts.DeckArrangement'),
        ),
    ]
