# Generated by Django 2.2.16 on 2021-01-01 20:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date(2021, 1, 1))),
                ('departure_time', models.DateField(default=None)),
                ('arrival_time', models.DateField(default=None)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('BEFORE_FLIGHT', 'Ready To Fly'), ('ONGOING', 'In Air'), ('LANDED', 'Landed')], default='NEW', max_length=12)),
            ],
        ),
    ]
