# Generated by Django 2.2.16 on 2021-01-03 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_auto_20210103_1510'),
        ('aircrafts', '0002_auto_20210103_1510'),
        ('users', '0002_auto_20210103_1510'),
        ('manifest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flights',
            name='aircraft',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='aircrafts.Aircraft'),
        ),
        migrations.AddField(
            model_name='flights',
            name='available_seats',
            field=models.IntegerField(null=True, verbose_name='only total numbers'),
        ),
        migrations.AddField(
            model_name='flights',
            name='club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='clubs.Club'),
        ),
        migrations.AddField(
            model_name='flights',
            name='pilots',
            field=models.ManyToManyField(to='users.User'),
        ),
        migrations.AlterField(
            model_name='flights',
            name='date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='flights',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('B_F', 'Ready To Fly'), ('ONG', 'In Air'), ('LND', 'Landed')], default='NEW', max_length=3),
        ),
    ]
