# Generated by Django 2.2.16 on 2021-01-03 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210103_1510'),
        ('aircrafts', '0002_auto_20210103_1510'),
        ('clubs', '0004_auto_20210103_1701'),
        ('manifest', '0002_auto_20210103_1510'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Flights',
            new_name='Flight',
        ),
    ]
