# Generated by Django 2.2.16 on 2021-01-04 07:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('manifest', '0003_auto_20210103_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 1, 4, 7, 30, 6, 863839, tzinfo=utc)),
        ),
    ]
