# Generated by Django 2.2.16 on 2021-01-04 07:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('manifest', '0005_auto_20210104_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='arrival_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 4, 7, 35, 0, 85599, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='flight',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 1, 4, 7, 35, 0, 85564, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 4, 7, 35, 0, 85586, tzinfo=utc)),
        ),
    ]
