# Generated by Django 2.2.16 on 2021-01-04 07:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('manifest', '0007_auto_20210104_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='arrival_time',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 1, 4, 7, 49, 18, 152378, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_time',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
