# Generated by Django 2.2.16 on 2021-01-04 07:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manifest', '0008_auto_20210104_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='date',
            field=models.DateField(default=datetime.date(2021, 1, 4)),
        ),
    ]
