# Generated by Django 2.2.16 on 2021-01-04 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manifest', '0009_auto_20210104_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='available_seats',
            field=models.IntegerField(null=True),
        ),
    ]
