# Generated by Django 2.2.16 on 2021-01-06 19:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manifest', '0010_auto_20210104_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='date',
            field=models.DateField(default=datetime.date(2021, 1, 6)),
        ),
    ]
